name: scraping
on:
  workflow_dispatch:
jobs:
  scraping:
    runs-on: ubuntu-latest
    environment:
      name: dev
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: set up node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: check out
        uses: actions/checkout@v2
      - name: install package
        run: |
          sudo apt update
          npx npm-check-updates chromedriver -u
          yarn
      - name: install chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb
         chrome --version
      - name: run script
        run: yarn run-kaldi
      - name: create a pull request
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: update sale_info_yyyymmdd.json
          signoff: false
          title: update sale_info_yyyymmdd.json
          delete-branch: true
          labels: |
            auto_merge
            hook
          branch: "create-pull-request/"
          branch-suffix: "short-commit-hash"
          draft: false
      - name: auto merge
        run: gh pr merge ${{ steps.pr.outputs.pull-request-url }} --merge
